name: Run Script and Push Changes

on:
  push:
    branches:
      - dev  # 监控 dev 分支的推送

jobs:
  run-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitPython

      - name: Run autodo.sh
        run: |
          chmod +x ./autodo.sh  # 确保脚本可执行
          ./autodo.sh
      - name: Get length of MY_PAT
        run: |
          echo "Length of MY_PAT: ${#MY_PAT}"
        env:
          MY_PAT: ${{ secrets.MY_PAT }}

      - name: Commit changes
        run: | 
          git config --local user.email "formatjn2019@gmail.com"
          git config --local user.name "zx"
          git add .
          git commit -m "Run autodo.sh and update changes" || echo "No changes to commit"

      - name: Push changes to main branch
        run: |
          git config --local user.email "action@example.com"
          git config --local user.name "action"
          git add .
          git commit -m "Your commit message" || echo "No changes to commit"
          git push https://action:${{ secrets.MY_PAT }}@github.com/formatjn2019/action-test.git HEAD:main --force
          echo "Length of MY_PAT: ${#MY_PAT}"
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
